### ISSUE TITLE
Stops storing cookie & constantly re-authenticating.

### ISSUE THREAD

**Issue by CalebTodd** [gitlon/CASTER#7]
It doesn't seem to hold on to the cookie for some reason. Just started recently. Eventually ends up trying to open a ton of tabs to re-auth to the point where I have to close the browser. 

In other cases, it breaks my ability to authenticate to my SAML endpoint at all. I end up having to clear all of my cookies for it to work again.

**Comment by bedge** [comment]
Same here. Stopped working maybe 2 days ago.

**Comment by lantrix** [comment]
Same thing with the launching of thousands :-P of tabs

**Comment by gitlon** [comment]
Noted - we've seen the same behaviour.

I _think_ it is related to the values being scraped from the Amazon cookies.

Under investigation...

**Comment by nikoizs** [comment]
+1 , have the same issue , started a couple of days ago.
might be related to the new Chrome version ? ( Version 51.0.2704.106 (64-bit))

**Comment by rowleyaj** [comment]
@gitlon did you make any further progress on this? I believe your reasoning to be correct - the cookies don't seem to be updated by AWS now.

We were thinking of adding some kind of timer within the extension itself, and requiring login through the extension. Didn't want to attempt anything until your changes about internal state model had come through (#6)

**Comment by gitlon** [comment]
I made a start, but didnt get the model working for all edge cases.

Basically only a few services (eg CloudTrail) are storing the expiry time in the seance cookie any more. Everything else is relying on the per-minute _heartbeat_ - I think it is called 'aws service health' or similar - which doesnt return a time but will return an indicator that the SAML token has expired.

However - I'm probably not going to work on CASTER any more. Because this will work for us.

https://blogs.aws.amazon.com/security/post/Tx3GL3IZE3FIGB6/Enable-Your-Federated-Users-to-Work-in-the-AWS-Management-Console-for-up-to-12-H

Is anyone affected by the issue that cant change their ADFS or other SAML expiry?

**Comment by rowleyaj** [comment]
Thanks for the link @gitlon, i'll take a look at that, but sounds like it will replace our use case too.

**Comment by CalebTodd** [comment]
This worked as a more viable solution for us. Missed that they released this.
